project:
  type: website
  output-dir: docs

website:
  title: "The Sigmoid Tales"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: About
        file: about.qmd

format:
  html:
    theme: lux
    toc: true


